### ISSUE TITLE
Research electron api and framework integration

### ISSUE THREAD

**Issue by francium** [BigBlockDataChain/docs#6]

**Comment by francium** [comment]
@khand5 Please close this if it is complete. Provide a summary here if you feel it would be beneficial.

**Comment by khand5** [comment]
As of yet, Electron remains compatible with Node APIs. Complications do arise during runtime. Please read summary here; https://github.com/BigBlockDataChain/docs/blob/master/research/electron-limitations/Limitations%20Overview
